# 20230125

# OFFLINE

![](https://github.com/gkgkfndudals/TIL/blob/master/Study/img/20230125_1.png)

- Error는 치명적인 에러 → JVM이 죽는 경우, 해결못하는 문제이다. 그래서 unchecked 으로 분류한다.
- try catch는 엄청 느리다. 그래서 unchecked는 최대한 if문으로 해결하자.

- try 선언문에 선언된 객체들에 대해 자동 close 호출(finally 역할)

```java
package com.sw.gumi.excep;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
 
public class ATest {

	public ATest() {
		// 특정한 파일의 내용을 읽어오세요
		try (FileInputStream fis = new FileInputStream("a.txt")) {
			// 생성, open, 접속시도, 객체얻기
			// 실행
		} catch (Exception e) {

		}

//		FileInputStream fis = null;
//		try {
//			// 생성, open, 접속시도, 객체얻기
//			fis = new FileInputStream("a.txt");
//			// 실행
//
//			// 종료(자원 반납)
////			fis.close(); // 실행하다가 오류가 나면 못 닫으니까 컴파일 에러난다.
//		} catch (FileNotFoundException e) {
//
//		} finally {
//			// close, disconnect, null 처리
////			System.out.println(fis);
//			if (fis != null) {
//				try {
//					fis.close();
//				} catch (IOException e) {}
//			}
//		}
	}

	public static void main(String[] args) {
		new ATest();
	}

}
```

- 출력순서를 확인해보자. return, System.exit(0), 종료문이 없을때 각각의 출력을 확인해보자

```java
package com.sw.gumi.excep;

public class BTest {

	public BTest() {
		// TODO Auto-generated constructor stub
		int a = 10;
		try {
			System.out.println("1");
			return ; // finally를 하고 return으로 종료 -> end 출력 안함
//			System.exit(0); // 이건 자바를 완전 끄는것이므로 1만 출력
		} catch (NullPointerException e) {
			System.out.println("2");
		} catch (Exception e) {
			System.out.println("2");
		}
//		catch(NullPointerException e) { // 상속 관계이므로 위로 올려야된다.
//			System.out.println("2");
//		}
		finally {
			System.out.println("3");
		}
		System.out.println("end");

	}

	public static void main(String[] args) {
		new BTest();

	}

}
```

## throws

- 예외를 호출한 곳으로 전달

![](https://github.com/gkgkfndudals/TIL/blob/master/Study/img/20230125_2.png)

- 나보다 큰 부모로  throws  할 수 없다.
- 부모에서는 ClassNotFoundException인데 자식에서 재정의할때 Exception으로 부모(상위) Exception을 사용하면 안된다.

![](https://github.com/gkgkfndudals/TIL/blob/master/Study/img/20230125_3.png)

```java
package com.sw.gumi.excep;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class CTest {

	public CTest() throws FileNotFoundException {
		aa();
	}
	
	void aa() throws FileNotFoundException {
//		try {
			FileInputStream fis = new FileInputStream("");			
//		} catch(FileNotFoundException e) {}
	}
	
	public static void main(String[] args) throws FileNotFoundException {
//		new CTest();
		Scanner sc = new Scanner(System.in);
		String s = sc.next();
		int num = 0;
		try {
			num = Integer.parseInt(s); // 글자를 넣었을때 NumberFormatException
		} catch(NumberFormatException e)
		{
			num =0;
		}
		
		System.out.println(num + 1000);
		
		
	}

}
```

- 상속관계가 없는 여러 개의 Exception을 한번에 처리 할 수 있다.

![](https://github.com/gkgkfndudals/TIL/blob/master/Study/img/20230125_4.png)

## 사용자 정의

```java
package com.sw.gumi.excep;

import java.util.Random;

public class DTest {

	public DTest() {
		try {
			m1();			
		} 
//		catch(MyException e) { // e는 패키지.클래스이름 나온다.
		catch(Exception e) { // 자식에서 부모이므로 재정의 가능
			System.out.println("오류 처리" + e); // e == e.toString 은 같다.
			System.out.println("오류 처리" + e.toString());
			System.out.println("오류 처리 e.getMessage() " + e.getMessage()); //getMessage를 많이 쓴다.
		}
	}

	void m1() throws MyException { // throws 클래스명
//		Random random = new Random();
//		int type = new Random().nextInt(2);
		int type = 1;

		if (type == 0) {
			System.out.println("정상");
		} else {
//			System.out.println("오류");
//			MyException e = new MyException();
//			throw e; // throw 변수명
//			throw new MyException(); 
			throw new MyException("sw 오류"); 
		}
	}

	public static void main(String[] args) {
		new DTest();

	}

}

class MyException extends Exception {
//	String msg; 
	
	public MyException(String msg) {
//		super();
		super(msg);
//		this.msg = msg;
	}
	
//	@Override
//	public String toString() {
//		return "MyException [] msg : " + msg;
//	}
//	
}
```